CREATE TABLE "app_state" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "areas" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "areas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"color" text NOT NULL,
	CONSTRAINT "areas_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "campaign_areas" (
	"campaign_id" text NOT NULL,
	"area_id" integer NOT NULL,
	CONSTRAINT "campaign_areas_campaign_id_area_id_pk" PRIMARY KEY("campaign_id","area_id")
);
--> statement-breakpoint
CREATE TABLE "campaign_folders" (
	"campaign_id" text NOT NULL,
	"folder_id" integer NOT NULL,
	CONSTRAINT "campaign_folders_campaign_id_folder_id_pk" PRIMARY KEY("campaign_id","folder_id")
);
--> statement-breakpoint
CREATE TABLE "campaigns" (
	"id" text PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"brand" text NOT NULL,
	"agency" text NOT NULL,
	"year" text NOT NULL,
	"tier" text NOT NULL,
	"category" text NOT NULL,
	"url" text NOT NULL,
	"raw" text NOT NULL,
	"added_at" text DEFAULT (now() AT TIME ZONE 'utc') NOT NULL,
	"analysis" text,
	"transcript" text,
	"team" text,
	"idea" text,
	"insight" text,
	"board" text,
	"youtube_url" text
);
--> statement-breakpoint
CREATE TABLE "daily_picks" (
	"date" text PRIMARY KEY NOT NULL,
	"campaign_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "folders" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "folders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"created_at" text DEFAULT (now() AT TIME ZONE 'utc') NOT NULL,
	CONSTRAINT "folders_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "meta" (
	"campaign_id" text PRIMARY KEY NOT NULL,
	"favorite" integer DEFAULT 0 NOT NULL,
	"rating" integer,
	"status" text DEFAULT 'inbox' NOT NULL,
	"personal_note" text,
	CONSTRAINT "meta_rating_check" CHECK ("meta"."rating" IS NULL OR ("meta"."rating" >= 1 AND "meta"."rating" <= 5)),
	CONSTRAINT "meta_status_check" CHECK ("meta"."status" IN ('inbox', 'studied', 'reference'))
);
--> statement-breakpoint
CREATE TABLE "notes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"campaign_id" text NOT NULL,
	"body" text NOT NULL,
	"created_at" text DEFAULT (now() AT TIME ZONE 'utc') NOT NULL
);
--> statement-breakpoint
ALTER TABLE "campaign_areas" ADD CONSTRAINT "campaign_areas_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaigns"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_areas" ADD CONSTRAINT "campaign_areas_area_id_areas_id_fk" FOREIGN KEY ("area_id") REFERENCES "public"."areas"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_folders" ADD CONSTRAINT "campaign_folders_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaigns"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_folders" ADD CONSTRAINT "campaign_folders_folder_id_folders_id_fk" FOREIGN KEY ("folder_id") REFERENCES "public"."folders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_picks" ADD CONSTRAINT "daily_picks_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaigns"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "meta" ADD CONSTRAINT "meta_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaigns"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notes" ADD CONSTRAINT "notes_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaigns"("id") ON DELETE no action ON UPDATE no action;